name: Java CI with Maven

on:
  push:
    branches: [ "master","ArokszallasiRichardLaszlo","DobosMilanImre","BalintLaszlo"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Java 21 environment
      - name: Set up OpenJDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Maven build and test
      - name: Build with Maven
        run: mvn -B package

      - name: Run tests
        run: mvn test


  # Deploy job (if you have a staging environment or some automated deploy)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy only happens after a successful build

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging
        run: |
          echo "Deploying to staging server..."
          
