name: Java CI with Maven

on:
  push:
    branches: [ "master","ArokszallasiRichardLaszlo","DobosMilanImre","BalintLaszlo"]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up OpenJDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'openjdk'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
